export const style = {
  position: "absolute" as "absolute",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  flexDirection: "column",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 400,
  bgcolor: "background.paper",
  border: "1px solid #ddd",
  boxShadow: 24,
  p: 4,
};
